baseURL = 'https://namkwangwoo.github.io/namkwangwoo.github.io/'
languageCode = 'ko-kr'
title = '초안 블로그'
description = '이 블로그는 개인적인 공간으로, 생각, 아이디어, 경험을 공유합니다.'
theme = "papermod"

[taxonomies]
  tag = 'tags'
